version: "3.9"
services:
  app:
    container_name: sports-complex-node
    restart: always
    build: .
    ports:
      - "5000:3000"
    env_file:
      - .env
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
